name: _deploy-aonec-base

on:
  workflow_call:
    inputs:
      deploy_script_name:
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on Gateway Virtual Machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YCGATEHOST_AONEC }}
          username: ${{ secrets.YCDEPLOYUSERNAME_AONEC }}
          key: ${{ secrets.YCDEPLOYUSERSERT_AONEC }}
          script: |
            cd /home/aonecroot/deploy_scripts
            ./${{ inputs.deploy_script_name }}
